### DISCUSSION TITLE
Has anyone else found that some endpoints can be viewed in a browser but the download is 0 bytes?

### DISCUSSION THREAD

**Discussion by withviz** [githubocto/flat-action#41] [Q&A]
I have an endpoint that works within a browser but fails to download the data to a file.

My `flat.yaml` is 

```
name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      # This step installs Deno, which is a new Javascript runtime that improves on Node. Can be used for an optional postprocessing step
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      # Check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      # The Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: endpoint
          downloaded_filename: data.json 
          #postprocess: ./postprocess.ts

```
Could it be that `http_url` is refused connection?
The action sucessfully runs but no data is downloaded.
