### DISCUSSION TITLE
Using Flat Data With Neo4j

### DISCUSSION THREAD

**Discussion by johnymontana** [githubocto/flat-action#54] [Flat in Action]
Hi Folks 👋 

I've been experimenting with using Flat Data to import data into Neo4j.

To make this workflow easier I published an Action called [Flat Graph](https://github.com/marketplace/actions/flat-graph) that allows for defining an Action step that includes the database connection credentials and a database query (using Cypher, the query language for Neo4j) to run that handles importing the data fetched by the Flat action in the previous step. For example, here's how you would use it to import data from the [Lobsters](https://lobste.rs) JSON feed:

```yml
name: Flat Graph for Neo4j

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Fetch newest 
        uses: githubocto/flat@v2
        with:
          http_url: https://lobste.rs/newest.json
          downloaded_filename: newest.json
      - name: Neo4j import
        uses: johnymontana/flat-graph@v1.1
        with:
          neo4j-user: ${{secrets.NEO4J_USER}}
          neo4j-password: ${{secrets.NEO4J_PASSWORD}}
          neo4j-uri: ${{secrets.NEO4J_URI}}
          filename: 'newest.json'
          cypher-query: >
              UNWIND $value AS article
              MERGE (u:User {username: article.submitter_user.username})
              MERGE (a:Article {id: article.short_id})
              SET a.url           = article.url,
                  a.id_url        = article.short_id_url,
                  a.created_at    = article.created_at,
                  a.title         = article.title,
                  a.score         = article.score,
                  a.flags         = article.flags,
                  a.comment_count = article.comment_count,
                  a.description   = article.description,
                  a.comments_url  = article.comments_url
              MERGE (u)-[:SUBMITTED]->(a)
              WITH article, a
              UNWIND article.tags AS tag
              MERGE (t:Tag {name: tag})
              MERGE (a)-[:HAS_TAG]->(t)        
```

To see it in action [I wrote a tutorial / blog post showing how to use Flat Data + Neo4j.](https://lyonwj.com/blog/no-cost-data-scraping-github-actions-neo4j-aura)

Would love to know what folks think of this workflow or any suggestions on how to improve it.

Cheers,
Will
